### ISSUE TITLE
Bucket stack size of 2 or more gets set to 1 when bucketing out liquids from the Inferno Forge

### ISSUE THREAD

**Issue by MageOfGaming** [AranaiRa/MagnumOpus#4]
**Minecraft Version:** 1.20.1

**MagiChem Version:** 0.4.2

**Steps to Reproduce:** 

- Get 2 ore more Empty Buckets into a single Slot
- Right click a inferno forge containing at least 1000mb Smoke

Also I'm pretty certain that this is a issue with any liquid and any elemental actuator but I haven't tested it yet
It also voids the rest of the buckets in the itemstack, I should have clarified that if that wasn't obvious yet :D

**Comment by AranaiRa** [comment]
Fixed for 0.4.3.
